// Generated by https://quicktype.io

export interface Data {
    total: number;
    hits:  Things[];
}

export interface Things {
    id:               number;
    name:             string;
    url:              string;
    public_url:       string;
    created_at:       string;
    thumbnail:        string;
    preview_image:    string;
    creator:          Creator;
    is_private:       null;
    is_purchased:     null;
    is_published:     null;
    is_featured:      boolean;
    is_edu_approved:  boolean;
    is_printable:     boolean;
    is_winner:        boolean;
    comment_count:    number;
    make_count:       number;
    like_count:       number;
    tags:             Tag[];
    is_nsfw:          boolean;
    rank:             number | null;
    collect_count:    number;
    moderation:       string;
    is_banned:        boolean;
    needs_moderation: null;
    winner_name?:     string;
    winner_link?:     string;
}

export interface Creator {
    id:                 number;
    name:               string;
    first_name:         string;
    last_name:          string;
    url:                string;
    public_url:         string;
    thumbnail:          string;
    count_of_followers: number;
    count_of_following: number;
    count_of_designs:   number;
    collection_count:   number;
    make_count:         number;
    accepts_tips:       boolean;
    is_following:       boolean;
    location:           string;
    cover:              string;
    is_admin:           number;
}

export interface Tag {
    name:         string;
    tag:          string;
    url:          string;
    count:        number;
    things_url:   string;
    absolute_url: string;
}
